# Generated by Django 5.0.6 on 2024-06-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaProducto',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='iva',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='subtotal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(),
        ),
    ]
